name: mad_salo_mods # Your project name
description: "A Flutter project for car package visualization."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust based on your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Or your preferred linter version

flutter:
  uses-material-design: true

  # --- Assets Section ---
  # Loads all images in this specific folder
  assets:
    - assets/logos/
    - assets/images/honda/city_2021_2025/
    - assets/images/toyota/corolla_2020_2025/
    - assets/images/haval/h6_2020_2025/